# Conversion to YAML from Properties formar report
# Warnings:
# - The yaml file had comments which are lost in the refactoring!
spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:mysql://localhost:3306/ userdb
    username: root
    password: Dibya@123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
cloud:
  config:
    server:
      git:
       uri: https://github.com/sonalitriya825-del/config-repo
       default-label: main				
server:
  port: 8081
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

